backend:
  name: github
  repo: jkwak09/cautious-guacamole
  branch: master
  api_root: https://api.github.com
  site_domain: cms.netlify.com

media_folder: static/assets
public_folder: /assets

collections:
  - name: blog-post
    label: Blog
    folder: 'content/blogs'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: posttype, label: Post Type, widget: "string", default: blog }
      - { name: thumbnail, label: "Featured Image", widget: "image" }
      - { name: altText, label: "Featured Image Description", widget: "string" }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }

  - name: project-post
    label: Project
    folder: 'content/projects'
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: posttype, label: Post Type, widget: "string", default: project }
      - { name: thumbnail, label: "Featured Image", widget: "image" }
      - { name: altText, label: "Featured Image Description", widget: "string" }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }